# Generated by Django 3.1.1 on 2020-09-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_todoitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.TextField(null='hi'),
            preserve_default='hi',
        ),
    ]
